# Profile
spring:
  profiles:
    active: local
    group:
      local: logging-type-console, logging-level-local
      dev: logging-type-file, logging-level-dev

  # H2 JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create    # DB 초기화 전략
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true      # 쿼리 로그 포맷 정렬
        show_sql: true        # 쿼리 로그 출력


  # Postgresql JPA 설정
#  jpa:
#    hibernate:
#      ddl-auto: none    # create같은 설정의 경우 schema.sql , data.sql 사용하여 JPA DB 생성

  # H2 Database 설정
  datasource:
    url: jdbc:h2:mem:test       # In-Memory
    #url: jdbc:h2:~/test      # Embedded
    driver-class-name: org.h2.Driver
    username: test      # 사용자 지정
    password: test123   # 사용자 지정. TODO : 직접 사용하지 않도록 수정 필요

  # H2 Console 설정
  h2:
    console:
      enabled: true         # H2 Console 사용 여부
      path: /h2-console     # H2 Console 접속 주소

  # Postgresql 설정
#  datasource:
#    url: jdbc:postgresql://localhost:15432/postgres
#    driver-class-name: org.postgresql.Driver
#    username: test
#    password: test123   # TODO : 직접 사용하지 않도록 수정 필요

